### ISSUE TITLE
Logging out as admin doesn't fully reset admin status

### ISSUE THREAD

**Issue by jbehaege** [vahicode/website#1]
The page turns white when clicking on an eye, a number or a picture.

**Comment by joostdecock** [comment]
From email:

> I can upload and save the files now, but the system does not always work. After grading one eye I’m not able to go back to the page of the grading scale. When I click on the eye, the number or the picture,  the page just turns white.

**Comment by joostdecock** [comment]
There are two different types of *login* on the system. You can login as an administrator at https://vahi.eu/admin or you can login as a user at https://vahi.eu/invite

The latter mightn't feel like logging in because you're only using an invite code, but behind the scenes, it's the same thing.

The behaviour you describe above is cause for your problems. Specifically you write:

> I can **upload and save the files now**, but the system does not always work. After _grading one eye_ I’m not able to go back to the page of the grading scale. When I **click on the eye, the number or the picture**, the page just turns white.

The actions that I have marked in **bold** require for you to be logged in as an **admin**.
The actions in _italics_ require that you are logged in as a _user_.

So, you log in as an admin, upload pictures and do your thing. Then you put in an invite code to test. At this moment you are logged in as a user and no longer as an admin.
You then try to do admin stuff, and obviously it doesn't work.

The real problem  here is this:

- After you've logged out as an admin, you still have the admin menu in the toolbar
- Access to admin pages works, but you can't do anything, or the pages that let you do something don't show up (or become white as you say).

So the issue at hand here is that it is not made sufficiently clear by the UI that you are no longer logged in as an admin, and should re-login to do admin stuff.

I will update the title of this issue accordingly, and look into fixing it.

**Comment by joostdecock** [comment]
Fixed in https://github.com/vahicode/website/commit/fb2d836a826e361a5039ead7b132ea0f7ed9090e
