### ISSUE TITLE
Issue with uploading pictures

### ISSUE THREAD

**Issue by jbehaege** [vahicode/website#10]
I'm not able to upload some of the pictures. I think because I uploaded them already before, even though they're not present in the system anymore. I encounter no problems with uploading new pictures.

**Comment by joostdecock** [comment]
I was not able to reproduce this. When you upload a picture that exists, it won't work since it's already there.
But if you remove the picture and upload the same one again, it works fine.

Perhaps you thought the picture was not present because it was not attached to any eye, rather than not in the system (as in, show up in the pictures table).
