### ISSUE TITLE
Rating vascularisation and haze vs rating integrity. 

### ISSUE THREAD

**Issue by jbehaege** [vahicode/website#6]
Vascularisation and haze should be graded using the normal white pictures with eye on top of it. 
Integrity needs to be graded using only the blue picture, and without eye.

**Comment by joostdecock** [comment]
I took a stab at this, please make sure to test it. Also, a few notes:

**Adding pictures to eyes**
I've added a way to add a picture to an existing eye. It used to be that you would select the pictures at the time you created the eye, and then had no way to add another one.
Since you might want to add these integrity pictures, I figured you might need that.

So, when you go to the admin -> add eyes page, you see all the unassigned pictures there.
You used to have two choices:
 - Create a new eye for each picture
 - Create eye with a bunch of pictures you select

Now you have a third option:

- Add the selected pictures to a new eye

When you pick that one, you'll see a list of eye ids and notes, and have to select to which eye you want to add these pictures. Then click the shiny new button.

**Setting the integrity picture for an eye**

We also need a way to tell the system that this picture is the *special integrity picture* or the *blue* pictures as you call them.
For that, go to the page where you can change the eye settings (notes and such). You'll see that it now also shows a thumbnail of all pictures associated with the eye.
Simply click the picture you want to be the integrity picture and save the eye.

**Rating eyes**

When rating, steps 1 and 2 will show the regular pictures + grid. In step 3 (integrity) they will make way for the integrity picture. You rate is as you do with the grid => Just click it to cycle through the scores.
The border of the picture will be coloured to indicate the score.

---

These changes have been deployed, so you can try it yourself at [vahi.eu](https://vahi.eu/).
